env:
  commonjs: true
  es6: true
extends:
  - "plugin:vue/essential"
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
settings:
  react:
    pragma: React
    version: latest
plugins:
  - prettier
  - react
  - vue
rules: { "prettier/prettier": "error", "linebreak-style": 0 }
